# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/msm8916-common/setup-makefiles.sh

SRC_DIR := vendor/asus/msm8916-common/proprietary

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Bluetooth_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_General_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_General_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Global_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Global_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Handset_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Handset_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Hdmi_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Hdmi_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Headset_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Headset_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Speaker_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Speaker_cal.acdb

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Bluetooth_cal_default.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal_default.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Bluetooth_cal_ZD550KL.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal_ZD550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_General_cal_default.acdb:system/etc/acdbdata/MTP/MTP_General_cal_default.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_General_cal_ZD550KL.acdb:system/etc/acdbdata/MTP/MTP_General_cal_ZD550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Global_cal_default.acdb:system/etc/acdbdata/MTP/MTP_Global_cal_default.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Global_cal_ZD550KL.acdb:system/etc/acdbdata/MTP/MTP_Global_cal_ZD550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Handset_cal_default.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal_default.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Handset_cal_ZD550KL.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal_ZD550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Hdmi_cal_default.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal_default.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Hdmi_cal_ZD550KL.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal_ZD550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Headset_cal_default.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal_default.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Headset_cal_ZD550KL.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal_ZD550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Speaker_cal_default.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal_default.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/MTP_Speaker_cal_ZD550KL.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal_ZD550KL.acdb

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/MTP_Bluetooth_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/MTP_Bluetooth_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/MTP_General_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/MTP_General_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/MTP_Global_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/MTP_Global_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/MTP_Handset_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/MTP_Handset_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/MTP_Hdmi_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/MTP_Hdmi_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/MTP_Headset_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/MTP_Headset_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/MTP_Speaker_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/MTP_Speaker_cal_ZE550KL.acdb

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Bluetooth_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Bluetooth_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_General_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_General_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Global_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Global_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Handset_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Handset_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Hdmi_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Hdmi_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Headset_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Headset_cal_ZE550KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Speaker_cal_ZE550KL.acdb:system/etc/acdbdata/MTP/ZE550KL/PR/MTP_PR_Speaker_cal_ZE550KL.acdb

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE600KL/MTP_Bluetooth_cal_ZE600KL.acdb:system/etc/acdbdata/MTP/ZE600KL/MTP_Bluetooth_cal_ZE600KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE600KL/MTP_General_cal_ZE600KL.acdb:system/etc/acdbdata/MTP/ZE600KL/MTP_General_cal_ZE600KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE600KL/MTP_Global_cal_ZE600KL.acdb:system/etc/acdbdata/MTP/ZE600KL/MTP_Global_cal_ZE600KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE600KL/MTP_Handset_cal_ZE600KL.acdb:system/etc/acdbdata/MTP/ZE600KL/MTP_Handset_cal_ZE600KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE600KL/MTP_Hdmi_cal_ZE600KL.acdb:system/etc/acdbdata/MTP/ZE600KL/MTP_Hdmi_cal_ZE600KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE600KL/MTP_Headset_cal_ZE600KL.acdb:system/etc/acdbdata/MTP/ZE600KL/MTP_Headset_cal_ZE600KL.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/MTP/ZE600KL/MTP_Speaker_cal_ZE600KL.acdb:system/etc/acdbdata/MTP/ZE600KL/MTP_Speaker_cal_ZE600KL.acdb

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb


PRODUCT_COPY_FILES += $(SRC_DIR)/bin/adsprpcd:system/bin/adsprpcd
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/soundfx/libicepower.so:system/lib/soundfx/libicepower.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so


PRODUCT_COPY_FILES += $(SRC_DIR)/bin/vm_bms:system/bin/vm_bms
PRODUCT_COPY_FILES += $(SRC_DIR)/bin/btnvtool:system/bin/btnvtool
PRODUCT_COPY_FILES += $(SRC_DIR)/bin/hci_qcomm_init:system/bin/hci_qcomm_init
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so


PRODUCT_COPY_FILES += $(SRC_DIR)/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/hw/camera.vendor.msm8916.so:system/lib/hw/camera.vendor.msm8916.so

PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libarcsoft_beautyshot.so:system/lib/libarcsoft_beautyshot.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libarcsoft_panorama_burstcapture.so:system/lib/libarcsoft_panorama_burstcapture.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libcameraap.so:system/lib/libcameraap.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libcamera_defocus.so:system/lib/libcamera_defocus.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libcamera_pano.so:system/lib/libcamera_pano.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libjpeggifcodec.so:system/lib/libjpeggifcodec.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libmorpho_panorama_gp.so:system/lib/libmorpho_panorama_gp.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libmpbase.so:system/lib/libmpbase.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libsphere3.so:system/lib/libsphere3.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libqomx_core.so:system/lib/libqomx_core.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/style.cng:system/lib/style.cng

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_a3907_camcorder.so:system/vendor/lib/libactuator_a3907_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_a3907_camera.so:system/vendor/lib/libactuator_a3907_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_a3907.so:system/vendor/lib/libactuator_a3907.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so:system/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_q13n04a_camera.so:system/vendor/lib/libactuator_dw9714_q13n04a_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_q13n04a.so:system/vendor/lib/libactuator_dw9714_q13n04a.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libactuator_dw9714_q13v04b_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9716_camcorder.so:system/vendor/lib/libactuator_dw9716_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9716_camera.so:system/vendor/lib/libactuator_dw9716_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_iu074_camcorder.so:system/vendor/lib/libactuator_iu074_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_iu074_camera.so:system/vendor/lib/libactuator_iu074_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_iu074.so:system/vendor/lib/libactuator_iu074.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_ov12830_camcorder.so:system/vendor/lib/libactuator_ov12830_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_ov12830_camera.so:system/vendor/lib/libactuator_ov12830_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_ov12830.so:system/vendor/lib/libactuator_ov12830.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_ov8825_camcorder.so:system/vendor/lib/libactuator_ov8825_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_ov8825_camera.so:system/vendor/lib/libactuator_ov8825_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_ov8825.so:system/vendor/lib/libactuator_ov8825.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_mn34150.so:system/vendor/lib/libmmcamera_mn34150.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_mn34150_asus_common.so:system/vendor/lib/libchromatix_mn34150_asus_common.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_mn34150_asus_preview_binning.so:system/vendor/lib/libchromatix_mn34150_asus_preview_binning.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_mn34150_asus_preview_full.so:system/vendor/lib/libchromatix_mn34150_asus_preview_full.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_mn34150_asus_preview_video.so:system/vendor/lib/libchromatix_mn34150_asus_preview_video.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_ov5670_asus_common.so:system/vendor/lib/libchromatix_ov5670_asus_common.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_ov5670_asus_gt_common.so:system/vendor/lib/libchromatix_ov5670_asus_gt_common.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_ov5670_asus_gt_preview_full.so:system/vendor/lib/libchromatix_ov5670_asus_gt_preview_full.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_ov5670_asus_preview_full.so:system/vendor/lib/libchromatix_ov5670_asus_preview_full.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_t4k35.so:system/vendor/lib/libmmcamera_t4k35.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_common_8916.so:system/vendor/lib/libchromatix_t4k35_asus_common_8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_common_8939.so:system/vendor/lib/libchromatix_t4k35_asus_common_8939.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_preview_binning.so:system/vendor/lib/libchromatix_t4k35_asus_preview_binning.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_preview_full_8916.so:system/vendor/lib/libchromatix_t4k35_asus_preview_full_8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_preview_full_8939.so:system/vendor/lib/libchromatix_t4k35_asus_preview_full_8939.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_preview_video_8916.so:system/vendor/lib/libchromatix_t4k35_asus_preview_video_8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_preview_video_8939.so:system/vendor/lib/libchromatix_t4k35_asus_preview_video_8939.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k35_asus_preview_video_binning.so:system/vendor/lib/libchromatix_t4k35_asus_preview_video_binning.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_t4k37.so:system/vendor/lib/libmmcamera_t4k37.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_common_8916.so:system/vendor/lib/libchromatix_t4k37_asus_common_8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_common_8939.so:system/vendor/lib/libchromatix_t4k37_asus_common_8939.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_preview_binning.so:system/vendor/lib/libchromatix_t4k37_asus_preview_binning.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_preview_full_8916.so:system/vendor/lib/libchromatix_t4k37_asus_preview_full_8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_preview_full_8939.so:system/vendor/lib/libchromatix_t4k37_asus_preview_full_8939.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_preview_video_8916.so:system/vendor/lib/libchromatix_t4k37_asus_preview_video_8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_preview_video_8939.so:system/vendor/lib/libchromatix_t4k37_asus_preview_video_8939.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37_asus_preview_video_binning.so:system/vendor/lib/libchromatix_t4k37_asus_preview_video_binning.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmcamera_t4k37f.so:system/vendor/lib/libmmcamera_t4k37f.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37f_asus_binning_sum.so:system/vendor/lib/libchromatix_t4k37f_asus_binning_sum.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37f_asus_common.so:system/vendor/lib/libchromatix_t4k37f_asus_common.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37f_asus_preview_full.so:system/vendor/lib/libchromatix_t4k37f_asus_preview_full.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37f_asus_preview_video.so:system/vendor/lib/libchromatix_t4k37f_asus_preview_video.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37r_asus_binning_sum.so:system/vendor/lib/libchromatix_t4k37r_asus_binning_sum.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37r_asus_common.so:system/vendor/lib/libchromatix_t4k37r_asus_common.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37r_asus_preview_full.so:system/vendor/lib/libchromatix_t4k37r_asus_preview_full.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libchromatix_t4k37r_asus_preview_video.so:system/vendor/lib/libchromatix_t4k37r_asus_preview_video.so

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw


PRODUCT_COPY_FILES += $(SRC_DIR)/bin/qseecomd:system/bin/qseecomd
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libflp.so:system/vendor/lib/libflp.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libESXEGL_adreno.so:system/vendor/lib64/egl/libESXEGL_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib64/egl/libESXGLESv1_CM_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libESXGLESv2_adreno.so:system/vendor/lib64/egl/libESXGLESv2_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libRBEGL_adreno.so:system/vendor/lib64/egl/libRBEGL_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib64/egl/libRBGLESv1_CM_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/egl/libRBGLESv2_adreno.so:system/vendor/lib64/egl/libRBGLESv2_adreno.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libCB.so:system/vendor/lib/libCB.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libscale.so:system/vendor/lib/libscale.so

PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/bin/perfd:system/vendor/bin/perfd
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so


PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/bin/mm-pp-daemon:system/vendor/bin/mm-pp-daemon
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so


PRODUCT_COPY_FILES += $(SRC_DIR)/bin/irsc_util:system/bin/irsc_util
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libidl.so:system/vendor/lib/libidl.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so


PRODUCT_COPY_FILES += $(SRC_DIR)/bin/netmgrd:system/bin/netmgrd
PRODUCT_COPY_FILES += $(SRC_DIR)/bin/qmuxd:system/bin/qmuxd
PRODUCT_COPY_FILES += $(SRC_DIR)/bin/radish:system/bin/radish
PRODUCT_COPY_FILES += $(SRC_DIR)/bin/rfs_access:system/bin/rfs_access
PRODUCT_COPY_FILES += $(SRC_DIR)/bin/rmt_storage:system/bin/rmt_storage
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml
PRODUCT_COPY_FILES += $(SRC_DIR)/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml

PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so

PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libmllite.so:system/lib/libmllite.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libmplmpu.so:system/lib/libmplmpu.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib64/libinvensense_hal.so:system/lib64/libinvensense_hal.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib64/libmllite.so:system/lib64/libmllite.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib64/libmplmpu.so:system/lib64/libmplmpu.so


PRODUCT_COPY_FILES += $(SRC_DIR)/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib64/hw/sensors.msm8916.so:system/lib64/hw/sensors.msm8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so

PRODUCT_COPY_FILES += $(SRC_DIR)/bin/time_daemon:system/bin/time_daemon
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so


PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/hw/sound_trigger.primary.msm8916.so:system/vendor/lib/hw/sound_trigger.primary.msm8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DataSet/ISP_lib_set/8916/libxditk_isp.bin:system/lib/DataSet/ISP_lib_set/8916/libxditk_isp.bin
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DataSet/ISP_lib_set/8929/libxditk_isp.bin:system/lib/DataSet/ISP_lib_set/8929/libxditk_isp.bin
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DataSet/ISP_lib_set/8939/libxditk_isp.bin:system/lib/DataSet/ISP_lib_set/8939/libxditk_isp.bin
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DataSet/ispDB/ParameterDB.db:system/lib/DataSet/ispDB/ParameterDB.db
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DataSet/ditSCidGen/msgchk.db:system/lib/DataSet/ditSCidGen/msgchk.db

PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_BACK_HL.cfg:system/lib/DIT_AT_BACK_HL.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_BACK_NORMAL.cfg:system/lib/DIT_AT_BACK_NORMAL.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_BACK_PREVIEW.cfg:system/lib/DIT_AT_BACK_PREVIEW.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_BACK_SR.cfg:system/lib/DIT_AT_BACK_SR.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_BACK_VIDEO.cfg:system/lib/DIT_AT_BACK_VIDEO.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_FRONT_HL.cfg:system/lib/DIT_AT_FRONT_HL.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_FRONT_NORMAL.cfg:system/lib/DIT_AT_FRONT_NORMAL.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_FRONT_PRE.cfg:system/lib/DIT_AT_FRONT_PRE.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DIT_AT_FRONT_VIDEO.cfg:system/lib/DIT_AT_FRONT_VIDEO.cfg
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/DITConfig.cfg:system/lib/DITConfig.cfg

PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libsarcsoft.so:system/lib/libsarcsoft.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libxditk_ArcSoftMOD.so:system/lib/libxditk_ArcSoftMOD.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libxditk_AT.so:system/lib/libxditk_AT.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libxditk_ISP.so:system/lib/libxditk_ISP.so
PRODUCT_COPY_FILES += $(SRC_DIR)/lib/libxditk_SR.so:system/lib/libxditk_SR.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libxditk_DIT_MSM8916.so:system/vendor/lib/libxditk_DIT_MSM8916.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libxditk_DIT_Qualcomm.so:system/vendor/lib/libxditk_DIT_Qualcomm.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libxditk_mmcamera2_stats_algorithm.so:system/vendor/lib/libxditk_mmcamera2_stats_algorithm.so
PRODUCT_COPY_FILES += $(SRC_DIR)/vendor/lib/libxditk_Network.so:system/vendor/lib/libxditk_Network.so

